In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

In [2]:
dt = pd.read_csv("data.csv")

In [3]:
dt.head(10)

,I1,I3,I5,I7,I9,I11,I13,I15,I17,I19,I21,I23,I25,I27,I29,Target
0,0.1148,0.0808,0.0382,0.0260,0.0165,0.0000,0.0009,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,1
1,0.1158,0.0801,0.0382,0.0273,0.0158,0.0005,0.0001,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,1
2,0.1133,0.0788,0.0383,0.0256,0.0166,0.0000,0.0004,0.0003,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,1
3,0.1118,0.0787,0.0370,0.0258,0.0162,0.0008,0.0000,0.0004,0.0000,0.0005,0.0,0.0,0.0,0.0,0.0,1
4,0.1132,0.0786,0.0388,0.0254,0.0174,0.0017,0.0011,0.0000,0.0000,0.0014,0.0,0.0,0.0,0.0,0.0,1
5,0.1120,0.0786,0.0385,0.0246,0.0184,0.0011,0.0000,0.0009,0.0005,0.0004,0.0,0.0,0.0,0.0,0.0,1
6,0.1121,0.0783,0.0373,0.0253,0.0171,0.0002,0.0010,0.0027,0.0000,0.0003,0.0,0.0,0.0,0.0,0.0,1
7,0.1118,0.0790,0.0387,0.0257,0.0177,0.0003,0.0000,0.0002,0.0000,0.0000,0.0,0.0,0.0,0.0,0.0,1
8,0.1117,0.0783,0.0384,0.0259,0.0181,0.0016,0.0005,0.0003,0.0000,0.0009,0.0,0.0,0.0,0.0,0.0,1
9,0.1112,0.0795,0.0381,0.0270,0.0178,0.0004,0.0008,0.0017,0.0000,0.0021,0.0,0.0,0.0,0.0,0.0,1

In [4]:
X = dt.iloc[:, 0:9]
y = dt.iloc[:, 15]

In [5]:
X.head(10)

       I1      I3      I5      I7      I9     I11     I13     I15     I17
0  0.1148  0.0808  0.0382  0.0260  0.0165  0.0000  0.0009  0.0000  0.0000
1  0.1158  0.0801  0.0382  0.0273  0.0158  0.0005  0.0001  0.0000  0.0000
2  0.1133  0.0788  0.0383  0.0256  0.0166  0.0000  0.0004  0.0003  0.0000
3  0.1118  0.0787  0.0370  0.0258  0.0162  0.0008  0.0000  0.0004  0.0000
4  0.1132  0.0786  0.0388  0.0254  0.0174  0.0017  0.0011  0.0000  0.0000
5  0.1120  0.0786  0.0385  0.0246  0.0184  0.0011  0.0000  0.0009  0.0005
6  0.1121  0.0783  0.0373  0.0253  0.0171  0.0002  0.0010  0.0027  0.0000
7  0.1118  0.0790  0.0387  0.0257  0.0177  0.0003  0.0000  0.0002  0.0000
8  0.1117  0.0783  0.0384  0.0259  0.0181  0.0016  0.0005  0.0003  0.0000
9  0.1112  0.0795  0.0381  0.0270  0.0178  0.0004  0.0008  0.0017  0.0000

In [6]:
y.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [8]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
mlp = MLPClassifier(activation = "identity", hidden_layer_sizes=(10, 10, 10), max_iter=100)

In [10]:
mlp.fit(X_train, y_train)

c:\users\irfan\appdata\local\programs\python\python36\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

MLPClassifier(activation='identity', hidden_layer_sizes=(10, 10, 10),
              max_iter=100)

In [11]:
predictions = mlp.predict(X_test)

In [12]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions,digits=4))

[[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0 25  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  1 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 1  0  1  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 18  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  1
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0
  10  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0 19  0  0  0  0  0  0
   0  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 19  0  1  0  0
   0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 24  0  0  0
   0  0  0  0  2  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0 24  0  0
   0  0  2  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  0
   0  0  0  0  3  0  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0 15
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  1  0  0  0  0  0
  11  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0
   0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0
   0  0 18  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0  1  0  0
   0  0  0 24  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0
   0  0  0  0  8  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  0
   0  0  0  0  4  0 15]]
              precision    recall  f1-score   support

           1     0.9000    1.0000    0.9474        18
           2     1.0000    0.9130    0.9545        23
           3     0.9375    0.9375    0.9375        16
           4     1.0000    1.0000    1.0000        12
           5     0.9615    0.9615    0.9615        26
           6     1.0000    0.9615    0.9804        26
           7     1.0000    1.0000    1.0000        17
           8     1.0000    1.0000    1.0000        25
           9     1.0000    0.9630    0.9811        27
          10     0.9167    1.0000    0.9565        22
          11     0.9444    0.8947    0.9189        19
          12     1.0000    1.0000    1.0000        14
          13     0.9444    1.0000    0.9714        17
          14     1.0000    1.0000    1.0000        21
          15     1.0000    1.0000    1.0000        18
          16     0.8125    0.9286    0.8667        14
          17     0.8462    0.5238    0.6471        21
          18     0.9048    0.9048    0.9048        21
          19     0.8421    1.0000    0.9143        16
          20     0.9048    0.8636    0.8837        22
          21     1.0000    0.8889    0.9412        27
          22     0.9231    0.8276    0.8727        29
          23     0.8421    0.7619    0.8000        21
          24     0.9375    0.8824    0.9091        17
          25     0.5238    0.7857    0.6286        14
          26     0.9500    0.9048    0.9268        21
          27     0.9000    0.9474    0.9231        19
          28     0.8571    0.8571    0.8571        28
          29     0.4706    0.8000    0.5926        10
          30     0.9474    1.0000    0.9730        18
          31     0.7895    0.7143    0.7500        21

    accuracy                         0.9081       620
   macro avg     0.9050    0.9104    0.9032       620
weighted avg     0.9177    0.9081    0.9093       620

In [15]:
predictions

array([29, 30, 14, 30, 22,  9, 11,  5, 14, 29,  6, 24,  9, 11, 22, 26,  9,
       10, 10, 12, 11, 15, 27,  3, 30, 14,  8,  8, 26, 20, 12, 17,  2, 25,
       19, 21, 21, 18,  7, 16,  1,  9, 25, 28, 22, 18,  7, 13, 22, 27, 19,
       22, 31, 20,  1,  5,  4, 24, 24,  2, 20, 22,  2, 13, 25, 21, 10, 25,
       13,  5, 27, 16,  5, 25, 25, 15, 15, 26, 22, 20,  8,  9, 26, 21, 28,
        7, 15, 13, 25, 10,  3, 24, 27, 21, 25, 31, 11, 16,  9,  2,  6,  6,
       24, 22,  3, 31,  5,  7, 11,  8, 18,  6, 14, 26, 19, 29,  6, 10,  3,
       21, 13,  5, 21, 23, 23, 21, 15,  3,  9, 27,  5, 27, 13, 17,  8,  1,
        2, 11,  8,  4, 22, 30, 18,  6,  2, 12,  6, 30,  3, 31, 20, 23,  5,
       17, 30, 25,  2, 15, 20, 25, 25, 13, 25,  7, 19, 21, 18, 30, 25, 26,
        6,  5,  4, 20, 28,  5, 12, 28, 16, 31,  1, 25, 26, 21,  4, 20,  6,
       16, 19,  2, 12, 17, 25, 18, 29,  9,  1, 21, 29, 16, 28, 17,  7, 22,
        5,  8, 28,  9, 26, 10, 22, 18, 25, 11,  9, 18,  7, 28, 30, 27,  5,
       29, 10,  2, 10,  3,  6,  8,  4,  8, 10, 31, 28, 24, 13, 10,  6, 22,
       25, 30, 23,  2,  7,  9, 13, 21, 20, 30, 29, 14, 28, 27, 16, 18,  7,
       10, 19, 20, 20, 27, 18, 16, 18,  9, 29, 29, 17, 17, 20,  3, 15, 13,
       20, 21,  4, 26, 31,  1, 14, 13, 16,  7,  5, 13,  4,  8,  1, 28, 23,
       29, 17, 19,  1, 23,  2, 14, 21,  3, 23,  3, 11,  8, 10, 12, 16, 26,
       28, 28, 13, 19, 20, 11, 14,  8, 29,  8, 29, 19,  6,  8,  5, 23,  2,
        5,  3,  6,  5, 19, 12,  5,  5, 14,  1, 10, 15, 12,  3, 31,  4, 21,
       23, 27, 10, 27,  6, 15, 24,  8,  9, 18, 28,  2,  6,  7, 30, 31, 19,
       17, 13, 20, 19,  7, 18,  6, 11, 25, 12, 28,  1, 12, 11, 19, 22,  1,
       24,  2, 11, 23, 21, 20, 15, 30, 23, 14,  5, 15,  5, 30, 30, 22, 23,
        8,  1, 26,  2, 15, 21, 21, 31,  6, 10, 20, 27,  9, 17, 29, 10, 14,
        9,  7, 22,  8,  1,  9, 24, 18,  5, 25, 23,  9, 28,  8, 22,  1, 13,
        7, 31,  8, 14, 15,  1, 28, 22, 11, 26,  9, 15, 28, 25, 14, 11, 22,
       11,  6,  8, 29, 17,  8,  1, 23, 20, 28,  9, 19, 28,  9, 20, 26, 22,
       24,  5, 23, 18, 11, 12,  2, 27, 30, 10, 12,  5,  6, 28,  8, 10,  3,
        8, 21, 28,  4, 10, 31, 29,  9,  5, 28, 26, 26, 22, 22, 30, 26,  6,
        3, 30, 15, 19,  9,  5, 28,  8,  1, 28, 11,  7,  1,  3,  6, 18, 22,
       24, 14, 13, 18, 27,  3, 27, 14, 31, 27, 10, 16, 26, 20, 26, 30,  9,
        2, 20, 26, 27, 10,  9, 19, 24,  4, 21, 11, 18, 10,  9, 28, 16, 17,
        8,  6, 21, 18, 22, 14, 19, 21, 24,  5, 22, 24, 14, 18, 31,  7,  4,
       23, 31, 10,  6,  1, 13, 21, 12, 31, 27, 19,  6, 31, 24, 15, 31, 17,
        4, 16, 13, 23, 18, 29, 15, 14,  7, 31, 30, 23, 16,  2, 14, 29, 12,
       25, 10, 28, 21, 28, 16, 14, 24, 26,  2, 22, 22,  2, 28,  9, 23, 15,
       16,  1, 14, 19,  2,  6, 27, 27], dtype=int64)

In [16]:
nilai= np.array([0.3188,0.1244,0.0154,0.0217,0.0183,0,0.0105,0.003,0.0017])

In [22]:
nilai=nilai.reshape(1,9)

In [23]:
nilai.shape
print(nilai)

[[0.3188 0.1244 0.0154 0.0217 0.0183 0.     0.0105 0.003  0.0017]]

In [24]:
a=mlp.predict(nilai)

In [25]:
print(a)

[22]